variable "rg_name" {}
variable "location" {}
variable "cluster_name" {}
variable "kubernetes_version" {}
variable "sku_tier" {}
variable "orchestrator_version" {}
variable "node_pool_name" {}
variable "vm_size" {}
variable "private_cluster_enabled" {}
variable "os_disk_type" {}
variable "vnet_subnet_id" {}
variable "enable_auto_scaling" {}
variable "node_count" {}
variable "enable_node_public_ip" {}
variable "node_availability_zones" {}
variable "node_type" {}
variable "node_max_pods" {}
#variable "net_plugin" {}
#variable "lb_sku" {}
variable "idtype" {}
variable "enable_http_application_routing" {}
variable "enable_kube_dashboard" {}
variable "enable_azure_policy" {}
variable "dns_prefix" {}
variable "enable_host_encryption" {}
#variable "max_count" {}
#variable "min_count" {}
variable "os_disk_size_gb" {}
#variable "kubernetes_service_address_range" {}
#variable "kubernetes_dns_service_ip" {}
#variable "kubernetes_bridge_address_range" {}
#variable "network_policy" {}
variable "resource_name" {}
variable "datecreated" {}
variable "env"{}
variable "project"{}
variable "tenant_id" {}
variable "admin_group_object_id" {}
variable "log_analtics_workspace_id" {}
variable "acr_scope" {}